### ISSUE TITLE
Mypy results do not show up

### ISSUE THREAD

**Issue by sametmax** [DamnWidget/anaconda#521]
I have the last mypy installed on Ubuntu 16.04 64bits:

```
$ which mypy
/usr/local/bin/mypy
$ mypy --version
mypy 0.4.4
```

I have uninstalled and installed anaconda back again to be sure.

I have the following setting setup: 

  `  "mypy": true`

Despite this, having this in my file:
```
def test(i: int):
    return 1

test('test')
```
Doesn't trigger any linter warning. I do have pep8 linter warnings showing up. 

I ran mypy manually and the file, and it does show me the warning.

**Comment by DamnWidget** [comment]
Can you gist the contents of anaconda's jsonserver logs and paste the URL to that gist?

The logs could be found in:

* Linux: ~/.local/share/anaconda/logs/<project_name>/anaconda_jsonserver.log
* OS X: ~/Library/Logs/anaconda/<project_name>/anaconda_jsonserver.log

**Comment by sametmax** [comment]
Ok I did that and I got the error `RuntimeError("MyPy was not found")`. Mypy was installed, but not in the virtualenv of my project. So I installed it and it worked. 

The code responsible for it is:
```

try:
    from mypy import main as mypy
    MYPY_SUPPORTED = True
except ImportError:
    pass
```
But mypy is like flake8, note related to your current env. You should be able to have one mypy, tox or flake8 installed for the whole system.

Maybe anaconda should provide a fallback mypy install in case it's not importable, or at least offer to install it in the virtualenv if it detects it's not.

**Comment by DamnWidget** [comment]
I could not replicate the issue myself, I have `mypy-lang-0.4.4` installed globally on my system (used `pip` to install it as there are no Arch packages) and it was working just fine into anaconda project itself (that is the only Python project that I currently work on).

Then I did open a new ST3 window and created a new python file, I noticed that MyPy wasn't working on that file but really everything was a bit slow so I did check the logs and noticed that the josnserver was crashing every time that MyPy was trying to lint the file. As soon as I drag and drop the file into anaconda project ST3 window it start working fine, I don't use any virtualenv or fancy python interpreter for anaconda project just the system one so in both scenarios the python interpreter was the same one.

Obviously there is some kind of problem but is kind of weird, I will investigate further and come up with a solution.

**Comment by sametmax** [comment]
This is definitely tied to the virtualenv on my part, as I got:

	"settings":
	{
		"python_interpreter": "/home/user/.local/share/virtualenvs/tygs/bin/python"
	}

In my project settings file.

**Comment by DamnWidget** [comment]
This is resolved and waiting release

**Comment by DamnWidget** [comment]
This has been released already

**Comment by sametmax** [comment]
I tried uninstalling mypy from the virtualenv while keeping up at the OS level but it didn't work.

**Comment by DamnWidget** [comment]
Trust me, if your configured Python interpreter is able to see the mypy
module it has to work. Check your logs to make sure there is no other
problem.

**Comment by sametmax** [comment]
After a year mypy is still not working on Anaconda. Things I've tried:

- completely deleting anaconda, including cache, and reinstall;
- setting up:

```
    "mypy": true,
    "mypy_suppress_stub_warnings": true,
    "mypy_check_untyped_defs": true,
    "mypy_mypypath": "/home/user/.local/bin/mypy",
```

- installing mypy at the system level, locally and in the virtualenv.

All linters work, but:

```
def foo(a: int, b: int) -> int:
    return a + b

d = foo(1, '')
```

Doesn't trigger anything on mypy.

I'm using Ubuntu, the latest anaconda and ST and no errors show up in the console.

**Comment by DamnWidget** [comment]
Exactly what I told you in the previous comment more than one year ago :+1: 

P.S: And if you don't believe me, just read it again :)
